Repository CCBR/RENEE, pull requests merged in 2024-08, with the labels that each got.

#139 fix copy in safe mode
  .github/workflows/main.yaml
  CHANGELOG.md
  docs/RNA-seq/build.md
  pyproject.toml
  src/renee/__main__.py
  tests/test_build.py
Labels: bug, RENEE, ccbrpipeliner/7

#142 ci: fix job names
  .github/workflows/main.yaml
Labels: RENEE

#143 ci: pytest module import
  tests/test_cli.py
Labels: RENEE

#150 docs: use mike for multiple docs versions on website
  .github/workflows/docs.yml
  CHANGELOG.md
  docs/requirements.txt
  mkdocs.yml
Labels: RENEE

#94 Refactor the renee python package and move the GUI here
  CHANGELOG.md
  bin/redirect
  main.py
  pyproject.toml
  resources/CCBRlogo.png
  resources/nih-bnfo-logo.png
  src/renee/__main__.py
  src/renee/cache.py
  src/renee/conditions.py
  src/renee/dryrun.py
  src/renee/gui.py
  src/renee/initialize.py
  src/renee/run.py
  src/renee/setup.py
  src/renee/util.py
  tests/test_build.py
  tests/test_cache.py
  tests/test_cli.py
  tests/test_run.py
  tests/test_util.py
Labels: RENEE, ccbrpipeliner/7

#152 fix: switch image paths in README to perma URLs
  CHANGELOG.md
  README.md
Labels: documentation, RENEE

#154 fix: always load required modules
  CHANGELOG.md
  bin/redirect
Labels: RENEE

#156 Update doc website with more FAQs and expect output tab
  CHANGELOG.md
  docs/RNA-seq/images/gui_nx_renee.png
  docs/RNA-seq/output.md
  docs/troubleshooting.md
  mkdocs.yml
Labels: RENEE

#151 Use tools package
  pyproject.toml
  src/renee/__main__.py
  src/renee/cache.py
  src/renee/gui.py
  src/renee/initialize.py
  src/renee/orchestrate.py
  src/renee/run.py
  src/renee/setup.py
  src/renee/util.py
  tests/test_cache.py
  tests/test_run.py
  tests/test_util.py
Labels: RENEE

#157 chore: specify ccbr_tools version v0.1.0
  pyproject.toml
Labels: RENEE

#149 feat: rsem-generate-data-matrix for genes & isoforms
  CHANGELOG.md
  workflow/Snakefile
  workflow/rules/common.smk
Labels: RENEE

#136 Re-build human genome annotations with GDC fasta
  CHANGELOG.md
  README.md
  config/genomes/biowulf/hg19_19.json
  config/genomes/biowulf/hg19_36.json
  config/genomes/biowulf/hg38_30.json
  config/genomes/biowulf/hg38_34.json
  config/genomes/biowulf/hg38_36.json
  config/genomes/biowulf/hg38_38.json
  config/genomes/biowulf/hg38_41.json
  config/genomes/biowulf/hg38_45.json
  config/genomes/frce/hg19_19.json
  config/genomes/frce/hg19_36.json
  config/genomes/frce/hg38_30.json
  config/genomes/frce/hg38_34.json
  config/genomes/frce/hg38_36.json
  config/genomes/frce/hg38_38.json
  config/genomes/frce/hg38_41.json
  config/genomes/frce/hg38_45.json
  docs/RNA-seq/Resources.md
  docs/RNA-seq/build.md
  docs/RNA-seq/run.md
  src/renee/__main__.py
  src/renee/setup.py
  tests/test_cli.py
Labels: RENEE
